### ISSUE TITLE
could you only provide FaPN design?

### ISSUE THREAD

**Issue by eeric** [EMI-Group/FaPN#1]
I was interested in your FaPN model, could you only provide FaPN structure?

**Comment by eeric** [comment]
I find it that link:
https://github.com/EMI-Group/FaPN/blob/main/detectron2/modeling/backbone/fan.py

**Comment by ShihuaHuang95** [comment]
@eeric Many thanks for your interest in our work. And [fan](https://github.com/EMI-Group/FaPN/blob/main/detectron2/modeling/backbone/fan.py) is the implementation of our FaPN. Besides, there is no specific FaPN structure, FAM and FSM are two core modules, you can embed them into any upsampling place especially FPN structure. We have released more implementations, please have a look on [FaPN-full](https://github.com/ShihuaHuang95/FaPN-full).

**Comment by eeric** [comment]
thanks for @ShihuaHuang95
