### ISSUE TITLE
Can you give me this model?

### ISSUE THREAD

**Issue by Icebinge** [EMI-Group/FaPN#2]
Hello, I am very interested in your FaPN model. Seeing that the FPS of the COCO dataset is very high in semantic segmentation, can you give me this model? I want to reproduce it.
![image](https://user-images.githubusercontent.com/90198947/132226322-dfb1a696-2b9e-4051-b8ce-066335abca72.png)

**Comment by ShihuaHuang95** [comment]
I think that I have already made a response to this question via email. As we stated, we will release the real-time models in the near future. For more implementations of our FaPN, please consider taking a look at this repo [FaPN-full](https://github.com/ShihuaHuang95/FaPN-full), we have released the best MaskFormer + FaPN over ADE20K-150.
