### ISSUE TITLE
Multiplying upsampled features by 2

### ISSUE THREAD

**Issue by shkarupa-alex** [EMI-Group/FaPN#3]
Could you please explain what is the reason for multiplying feat_up by 2 here https://github.com/EMI-Group/FaPN/blob/main/detectron2/modeling/backbone/fan.py#L66 ?

**Comment by ShihuaHuang95** [comment]
Hi, thanks for your interest in our work. We enlarge the magnitude of upsampled features in case of suppression.

**Comment by UCAS-GYX** [comment]
> or your interest in our work. We enlarge the magnitude of upsampled features in case of suppression.

Thanks for your awesome work. Could you explain detailly? What happens if I don't multiply by 2 and have you ever tried to multiply by a learnable variable?

**Comment by ShihuaHuang95** [comment]
> > or your interest in our work. We enlarge the magnitude of upsampled features in case of suppression.
> 
> Thanks for your awesome work. Could you explain detailly? What happens if I don't multiply by 2 and have you ever tried to multiply by a learnable variable?

Sorry for the late reply. You can have a look at the [EDVR](https://github.com/xinntao/EDVR/tree/master/basicsr/models).
