### ISSUE TITLE
Is that possible replace dcnv2 plugin with torchvision dcn API?

### ISSUE THREAD

**Issue by luohao123** [EMI-Group/FaPN#4]
Hi, wonder:

1. Is that possible replace dcnv2 plugin with torchvision dcn API?
2. Can dcnv2 replaced with normal conv since dcn is not well supported in production. Also, will the performance drop a lot using normal conv?

**Comment by ShihuaHuang95** [comment]
Hi, many thanks for your interest in our work. 
1) We have not tried this, and maybe you can have a try; 
2) Deformable CNN is the core function to perform feature alignment which can be replaced with other alignment functions such as flow, while a normal conv is not an effective solution.
